---
- name: Remove directory
  file:
    path: /home/{{ user_name }}/{{ project_dir }}
    state: absent
  ignore_errors: yes

- name: Copy project folder
  copy:
    src: ./{{ project_dir }}
    dest: /home/{{ user_name }}

- name: Recursively change ownership of a directory
  file:
    path: /home/{{ user_name }}
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_name }}"