---
- hosts: all
  roles:
      #- add_boosta_admins
      #- create_iptables
      #- update
      #- create_user
      #- docker
      - dir_copy
      - swarm_init
  tasks:

    - name: Build an image
      docker_image:
        source: build
        build:
          path: "/home/{{ user_name }}/{{ var_build_path }}"
        name: "app/php-7.2-fpm"

    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: "{{ var_stack_name }}"
        compose:
          - /home/{{ user_name }}/{{ project_dir }}/docker-compose.yml

    - debug: var={{item}}
      with_items: stack_deploy.stdout_lines

    - name: Check list of services
      command: docker service ls
      register: service_list

    - debug: var={{item}}
      with_items: service_list.stdout_lines
